image: gitlab/dind

variables:
  USE_CONTAINER: "true"

before_script:
- apt-get update -yqqq
- apt-get install -yqqq make

test:
  stage: test
  script:
  - make fmt lint vet test-long
  tags:
  - docker
  - privileged

build:
  stage: build
  script:
  - make build
  artifacts:
    paths:
    - bin/
  tags:
  - docker
  - privileged
